  version = 1

  test_patterns = [
    "src/tests/**",
    "**/test_*.py"
  ]
  
  exclude_patterns = [
    "src/main.py"
  ]
  
  [[analyzers]]
  name = "python"
  enabled = true
  runtime_version = "3.x.x"
  
